### ISSUE TITLE
Publish the test.html doc on GitHub Pages

### ISSUE THREAD

**Issue by rijkvanzanten** [maanlamp/OBA-wrapper#6]
It would be incredibly useful to be able to play around with the demo `test.html` file without having to clone and install everything. You could keep a separate branch for this live demo or publish the whole master branch and add a link to the repo.

**Comment by maanlamp** [comment]
Because of the tight schedule I had for another project, I had little time to edit this. I had planned on doing this from the beginning.

Fixed as of https://github.com/maanlamp/OBA-wrapper/commit/c88a327e4c9c6ee4ff7b2b978cdb3e7b21025f2a
at https://github.com/maanlamp/OBA-wrapper/commit/c88a327e4c9c6ee4ff7b2b978cdb3e7b21025f2a#diff-04c6e90faac2675aa89e2176d2eec7d8R116
